// <auto-generated />
using System;
using EDI_Manager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EDI_Manager.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220503215941_Elections")]
    partial class Elections
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EDI_Manager.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"), 1L, 1);

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ClientTaxId")
                        .HasColumnType("int");

                    b.Property<string>("ContactMails")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactPhoneNumbers")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("EDI_Manager.Developer", b =>
                {
                    b.Property<int>("DeveloperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeveloperId"), 1L, 1);

                    b.Property<string>("DeveloperFirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DeveloperLastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DeveloperMail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeveloperRole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("DeveloperId");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("EDI_Manager.Feed", b =>
                {
                    b.Property<int>("FeedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedId"), 1L, 1);

                    b.Property<int?>("BusinessDayOfMonth")
                        .HasColumnType("int");

                    b.Property<int>("CarrierId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("DeveloperId")
                        .HasColumnType("int");

                    b.Property<string>("EndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FTPAccountId")
                        .HasColumnType("int");

                    b.Property<int>("FeedFrequencyId")
                        .HasColumnType("int");

                    b.Property<string>("FeedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FeedSecurityTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("FrequencyTimes")
                        .HasColumnType("int");

                    b.Property<int>("InProduction")
                        .HasColumnType("int");

                    b.Property<int>("IsChangesOnly")
                        .HasColumnType("int");

                    b.Property<string>("PGPPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Series")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceFileId")
                        .HasColumnType("int");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetFileMimeId")
                        .HasColumnType("int");

                    b.Property<int?>("TargetFileTypeFileMimeId")
                        .HasColumnType("int");

                    b.Property<int?>("WeeklyRecurDay")
                        .HasColumnType("int");

                    b.Property<string>("ZipPassword")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeedId");

                    b.HasIndex("CarrierId");

                    b.HasIndex("ClientId");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("FTPAccountId");

                    b.HasIndex("FeedFrequencyId");

                    b.HasIndex("FeedSecurityTypeId");

                    b.HasIndex("SourceFileId");

                    b.HasIndex("TargetFileTypeFileMimeId");

                    b.ToTable("Feeds");
                });

            modelBuilder.Entity("EDI_Manager.File", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileId"), 1L, 1);

                    b.Property<int>("FileMimeId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("FileId");

                    b.HasIndex("FileMimeId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("EDI_Manager.FileMime", b =>
                {
                    b.Property<int>("FileMimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileMimeId"), 1L, 1);

                    b.Property<string>("FileMimeName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("FileMimeId");

                    b.ToTable("FileMimes");
                });

            modelBuilder.Entity("EDI_Manager.SSHKey", b =>
                {
                    b.Property<int>("SSHKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SSHKeyId"), 1L, 1);

                    b.Property<string>("FTPHost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SSHKeyId");

                    b.ToTable("SSHKeys");
                });

            modelBuilder.Entity("EDI_Manager.TableDefinitions.Carrier", b =>
                {
                    b.Property<int>("CarrierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarrierId"), 1L, 1);

                    b.Property<string>("Adress1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarrierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CarrierTaxId")
                        .HasColumnType("int");

                    b.Property<int>("CarrierTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Phones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebSite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarrierId");

                    b.HasIndex("CarrierTypeId");

                    b.ToTable("Carriers");
                });

            modelBuilder.Entity("EDI_Manager.TableDefinitions.CarrierType", b =>
                {
                    b.Property<int>("CarrierTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarrierTypeId"), 1L, 1);

                    b.Property<string>("CarrierTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarrierTypeId");

                    b.ToTable("CarrierTypes");
                });

            modelBuilder.Entity("EDI_Manager.TableDefinitions.Child", b =>
                {
                    b.Property<int>("ChildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChildId"), 1L, 1);

                    b.Property<float?>("BenefitSalary")
                        .HasColumnType("real");

                    b.Property<string>("BusinessTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EligibilityPeriodEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EligibilityPeriodStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeNumber")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmploymentStatusEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EmploymentStatusStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnrollmentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("HomePhone")
                        .HasColumnType("bigint");

                    b.Property<int?>("HoursPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("IsCertified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsTestEmployee")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTobaccoUser")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsVoluntaryTermination")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberAddress1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MemberBirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MemberHireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberMiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MemberSsn")
                        .HasColumnType("bigint");

                    b.Property<string>("MemberState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MemberTerminationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberTerminationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MemberZip")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OriginalHireDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PayRate")
                        .HasColumnType("int");

                    b.Property<string>("PayType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayrollSchedule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QMCSO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Ssn")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StatusChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StatusEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StatusStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubscriberID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TerminationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Union")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerificationExpiresOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ChildId");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("EDI_Manager.TableDefinitions.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"), 1L, 1);

                    b.Property<float?>("BenefitSalary")
                        .HasColumnType("real");

                    b.Property<string>("BusinessTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EligibilityPeriodEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EligibilityPeriodStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeNumber")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmploymentStatusEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EmploymentStatusStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnrollmentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("HomePhone")
                        .HasColumnType("bigint");

                    b.Property<int?>("HoursPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("IsCertified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsTestEmployee")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTobaccoUser")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsVoluntaryTermination")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberAddress1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MemberBirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MemberHireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberMiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MemberSsn")
                        .HasColumnType("bigint");

                    b.Property<string>("MemberState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MemberTerminationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberTerminationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MemberZip")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OriginalHireDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PayRate")
                        .HasColumnType("int");

                    b.Property<string>("PayType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayrollSchedule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QMCSO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Ssn")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StatusChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StatusEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StatusStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubscriberID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TerminationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Union")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerificationExpiresOn")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EDI_Manager.TableDefinitions.FeedFrequency", b =>
                {
                    b.Property<int>("FeedFrequencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedFrequencyId"), 1L, 1);

                    b.Property<string>("FeedFrequencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeedFrequencyId");

                    b.ToTable("FeedFrequency");
                });

            modelBuilder.Entity("EDI_Manager.TableDefinitions.FeedSecurityType", b =>
                {
                    b.Property<int>("FeedSecurityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedSecurityTypeId"), 1L, 1);

                    b.Property<string>("FeedSecurityTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeedSecurityTypeId");

                    b.ToTable("FeedSecurityType");
                });

            modelBuilder.Entity("EDI_Manager.TableDefinitions.FTPAccount", b =>
                {
                    b.Property<int>("FTPAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FTPAccountId"), 1L, 1);

                    b.Property<string>("FTPDirectory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FTPHost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FTPPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FTPPort")
                        .HasColumnType("int");

                    b.Property<string>("FTPType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FTPUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FTPAccountId");

                    b.ToTable("FTPAccounts");
                });

            modelBuilder.Entity("EDI_Manager.TableDefinitions.Platform", b =>
                {
                    b.Property<int>("PlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlatformId"), 1L, 1);

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlatformId");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("EDI_Manager.TableDefinitions.Spouse", b =>
                {
                    b.Property<int>("SpouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpouseId"), 1L, 1);

                    b.Property<float?>("BenefitSalary")
                        .HasColumnType("real");

                    b.Property<string>("BusinessTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EligibilityPeriodEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EligibilityPeriodStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeNumber")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmploymentStatusEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EmploymentStatusStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnrollmentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("HomePhone")
                        .HasColumnType("bigint");

                    b.Property<int?>("HoursPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("IsCertified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsTestEmployee")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTobaccoUser")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsVoluntaryTermination")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberAddress1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MemberBirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MemberHireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberMiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MemberSsn")
                        .HasColumnType("bigint");

                    b.Property<string>("MemberState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MemberTerminationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberTerminationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MemberZip")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OriginalHireDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PayRate")
                        .HasColumnType("int");

                    b.Property<string>("PayType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayrollSchedule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QMCSO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Ssn")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StatusChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StatusEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StatusStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubscriberID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TerminationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Union")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerificationExpiresOn")
                        .HasColumnType("datetime2");

                    b.HasKey("SpouseId");

                    b.ToTable("Spouses");
                });

            modelBuilder.Entity("EDI_Manager.TableDefinitions.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EDI_Manager.Utilities.Election", b =>
                {
                    b.Property<string>("ElectionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Benefit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("BillingFee")
                        .HasColumnType("real");

                    b.Property<float?>("BillingFee2")
                        .HasColumnType("real");

                    b.Property<float?>("BillingPremium")
                        .HasColumnType("real");

                    b.Property<string>("Carrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CarrierEffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ChangeEffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CobraMappingCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CoverageTerminationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CoverageTerminationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DemographicEffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DomesticPartnerOrgPremiumAmount")
                        .HasColumnType("int");

                    b.Property<int?>("DomesticPartnerSubscriberPremiumAmount")
                        .HasColumnType("int");

                    b.Property<float?>("EEPostaxPremium")
                        .HasColumnType("real");

                    b.Property<float?>("EEPremium")
                        .HasColumnType("real");

                    b.Property<float?>("EEPretaxPremium")
                        .HasColumnType("real");

                    b.Property<int?>("ERPremium")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EffectiveDateForOrganizationYTD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveDateForSubscriberYTD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ElectionEffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployerAnnualAmount")
                        .HasColumnType("int");

                    b.Property<int?>("EmployerMonthlyAmount")
                        .HasColumnType("int");

                    b.Property<int?>("ExportMappingCode")
                        .HasColumnType("int");

                    b.Property<int?>("GroupNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("HSAContributionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HSAERLumpSum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("HSALumpSumPayDate")
                        .HasColumnType("datetime2");

                    b.Property<float?>("ImputedIncome")
                        .HasColumnType("real");

                    b.Property<int?>("IncrementsOrPercentage")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaximumVolumeAllowedAmount")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationYTD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OriginalEffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PayrollMappingCode")
                        .HasColumnType("int");

                    b.Property<string>("Plan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriorCarrierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PriorEffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PriorGroupNumber")
                        .HasColumnType("int");

                    b.Property<int?>("PriorMemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PriorTerminationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RequestedEmployerAnnualAmount")
                        .HasColumnType("int");

                    b.Property<int?>("RequestedEmployerMonthlyAmount")
                        .HasColumnType("int");

                    b.Property<int?>("RequestedIncrementsOrPercentage")
                        .HasColumnType("int");

                    b.Property<string>("RequestedLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RequestedSubscriberAnnual")
                        .HasColumnType("int");

                    b.Property<int?>("RequestedSubscriberMonthly")
                        .HasColumnType("int");

                    b.Property<int?>("RequestedVolume")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SignatureDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubscriberAnnual")
                        .HasColumnType("int");

                    b.Property<int?>("SubscriberMonthly")
                        .HasColumnType("int");

                    b.Property<int?>("SubscriberYTD")
                        .HasColumnType("int");

                    b.Property<int?>("Volume")
                        .HasColumnType("int");

                    b.Property<DateTime?>("WaivePlanTerminationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ElectionId");

                    b.ToTable("Elections");
                });

            modelBuilder.Entity("EDI_Manager.Feed", b =>
                {
                    b.HasOne("EDI_Manager.TableDefinitions.Carrier", "Carrier")
                        .WithMany()
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EDI_Manager.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EDI_Manager.Developer", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EDI_Manager.TableDefinitions.FTPAccount", "FTPAccount")
                        .WithMany()
                        .HasForeignKey("FTPAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EDI_Manager.TableDefinitions.FeedFrequency", "FeedFrequency")
                        .WithMany()
                        .HasForeignKey("FeedFrequencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EDI_Manager.TableDefinitions.FeedSecurityType", "FeedSecurityType")
                        .WithMany()
                        .HasForeignKey("FeedSecurityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EDI_Manager.File", "SourceFile")
                        .WithMany()
                        .HasForeignKey("SourceFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EDI_Manager.FileMime", "TargetFileType")
                        .WithMany()
                        .HasForeignKey("TargetFileTypeFileMimeId");

                    b.Navigation("Carrier");

                    b.Navigation("Client");

                    b.Navigation("Developer");

                    b.Navigation("FTPAccount");

                    b.Navigation("FeedFrequency");

                    b.Navigation("FeedSecurityType");

                    b.Navigation("SourceFile");

                    b.Navigation("TargetFileType");
                });

            modelBuilder.Entity("EDI_Manager.File", b =>
                {
                    b.HasOne("EDI_Manager.FileMime", "FileMime")
                        .WithMany()
                        .HasForeignKey("FileMimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileMime");
                });

            modelBuilder.Entity("EDI_Manager.TableDefinitions.Carrier", b =>
                {
                    b.HasOne("EDI_Manager.TableDefinitions.CarrierType", "CarrierType")
                        .WithMany()
                        .HasForeignKey("CarrierTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarrierType");
                });
#pragma warning restore 612, 618
        }
    }
}
